# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project_linertec' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project_linertec


pod 'Alamofire'
pod 'Kingfisher'
pod 'Toaster'
pod 'Firebase/Firestore'
pod 'DropDown'


end
